# Site settings
title: FAIr Game
email: your-email@domain.com
url: "https://macgenomegue.github.io"
baseurl: "/FAIr_Game"
description: "Explore interactive scenarios on academic integrity and ethical dilemmas with the SATLE-funded Fair Game project. Engage with gamified learning, test your decision-making skills, and enhance your understanding of responsible research and ethics in academia. Join us in fostering a culture of integrity and ethical awareness!"
keywords: "Academic Integrity, Ethical Dilemmas, Gamified Learning, Research Ethics, Responsible Conduct in Research, Higher Education Ethics, Integrity Training, Ethical Decision-Making"
skills: "Testing Academic Integrity"
meta_author: Guerrino Macori

# Contact form
contact: static
disqus_shortname: myshortname

# Color settings
color:
  primary: "18bc9c"
  primary-rgb: "24,188,156"
  secondary: "2c3e50"
  secondary-dark: "233140"

# Footer
footer:
  copyright: SATLE Team
  location: University College Dublin
  social: Connect with us
  credits: Fundings

# Social networks
social:
  - title: twitter
    url: "http://twitter.com/guerrinomacori"
  - title: facebook
    url:
  - title: github
    url: "http://github.com/macgenomegue"

# Address
address:
  - line: UCD SATLE Project
  - line: 

# Credits
credits: "The project has been supported by UCD, through funding from the National Forum/Higher Education Authority under the Strategic Alignment of Teaching and Learning Enhancement Fund (SATLE)."

# Build settings
markdown: kramdown
permalink: pretty

# Post defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""