# Site settings
title: FAIr Game
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Explore interactive scenarios on academic integrity and ethical dilemmas with the SATLE-funded Fair Game project. Engage with gamified learning, test your decision-making skills, and enhance your understanding of responsible research and ethics in academia. Join us in fostering a culture of integrity and ethical awareness!"
keywords: "Academic Integrity, Ethical Dilemmas,	Gamified Learning,	Research Ethics,	Responsible Conduct in Research, Higher Education Ethics, Integrity Training,	Ethical Decision-Making separated by commas"
skills: "Testing Academic Integrity"
meta_author: Guerrino Macori

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/guerrinomacori
  - title: facebook
    url:
  - title: github
    url: http://github.com/macgenomegue

# Postal address (add as many lines as necessary)
address:
  - line: UCD SATLE Project
  - line: 

# Credits content
credits: 'Welcome to the Fair Game project website, a hub for exploring academic integrity and ethical dilemmas through interactive and gamified learning. This project, funded by the SATLE (Strategic Alignment of Teaching and Learning Enhancement) initiative, has developed a collection of scenarios designed to challenge and engage students, educators, and researchers in navigating real-world ethical challenges. Here, you will find a curated selection of academic integrity dilemmas, ranging from responsible research practices to ethical decision-making in scientific and academic settings. These scenarios were collaboratively developed with students and faculty to provide meaningful insights into integrity-related challenges in higher education. The materials and resources available on this site can be used for training, discussion, and game-based learning, supporting a deeper understanding of ethical principles in academia. Explore the scenarios, test your decision-making skills, and join us in fostering a culture of integrity and responsibility!'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
